### ISSUE TITLE
Error during compile

### ISSUE THREAD

**Issue by ghost** [tomlokhorst/swift-json-gen#16]
Sorry for disturbing again ;-) I just got this error during swift-json-gen - any idea what the reason may be?

/usr/local/lib/node_modules/swift-json-gen/lib/SwiftPrinter.js:156
        if (keyType != 'String' && enum_.rawTypeName != 'String') {
                                        ^
TypeError: Cannot read property 'rawTypeName' of undefined
    at makeFieldEncode (/usr/local/lib/node_modules/swift-json-gen/lib/SwiftPrinter.js:156:41)
    at /usr/local/lib/node_modules/swift-json-gen/lib/SwiftPrinter.js:100:20
    at Array.forEach (native)
    at makeStructEncoder (/usr/local/lib/node_modules/swift-json-gen/lib/SwiftPrinter.js:99:21)
    at /usr/local/lib/node_modules/swift-json-gen/lib/SwiftPrinter.js:53:34
    at Array.forEach (native)
    at Object.makeFile (/usr/local/lib/node_modules/swift-json-gen/lib/SwiftPrinter.js:42:13)
    at /usr/local/lib/node_modules/swift-json-gen/lib/JsonGen.js:85:37
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)

**Comment by ghost** [comment]
Meanwhile I found out that this is caused by a struct that uses a Dictionary with an Int key. When changing that to String, the error disappears.

**Comment by ghost** [comment]
However, it would be rather useful to be able to have Int keys for Dictionaries... is it possible to support this?

**Comment by tomlokhorst** [comment]
Could you give an example of you code that caused this error?
I'd like to at least generate a better error.

Also, I don't think it's possible to have non-string keys in a JSON object.
